---
driver:
  name: docker

platforms:
  - name: ubuntu
    image: "ubuntu:20.04"    
    dockerfile: ../dockerfile  # Указываем путь к кастомному Dockerfile
    

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later
...
