---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Replace this task with one that validates your content
      apt:
        update_cache: yes
        name:          
          - vim
