---
driver:
  name: docker

platforms:
  - name: ubuntu
    image: ubuntu
    priveleged: true

dependency:
  name: galaxy

provisioner:
  name: ansible

scenario:
  test_sequence:
    - converge
    - verify
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
