---
# handlers file for complex_role
- name: Restart_mysql
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Restart_nginx
  ansible.builtin.command: /etc/init.d/nginx restart

- name: Restart MariaDB
  ansible.builtin.service:
    name: mariadb
    state: restarted
...
