- name: Ensure nginx is installed
  package:
    name: nginx
    update_cache: true
  notify: restart_nginx

- name: Создать новый самоподписанный сертификат
  openssl_certificate:
    path: '{{ tls_dir + cert_file }}'
    privatekey_path: '{{ tls_dir + key_file }}'
    provider: selfsigned       
    state: present
  
- name: Create directories for TLS certificates
  file:
    path: "{{ tls_dir }}"
    state: directory
    mode: '0750'      
  notify: restart_nginx

- name: Copy TLS files
  copy:
    src: "{{ item }}"
    dest: "{{ tls_dir }}"
    mode: '0600'
  loop:
    - "{{ key_file }}"
    - "{{ cert_file }}"
  notify: restart_nginx 

- name: Manage nginx config template
  template:
    src: nginx.conf.j2
    dest: "{{ conf_file }}"
    mode: '0644'
  notify: restart_nginx

- name: Enable configuration
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link      

- name: Install home page
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: '0644'

- name: restart_nginx
  meta: flush_handlers