---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: debian
    image: debian
    privileged: true
    docker_networks:
      - name: 'public_net'
    ipam_config:
      - subnet: '10.16.0.0/24'
    networks:
      - name: 'public_net'
    ipv4_address: '10.16.0.10'

  - name: ubuntu
    image: ubuntu
    privileged: true
    docker_networks:
      - name: 'private_net'
    ipam_config:
      - subnet: '10.16.0.0/24'
    networks:
      - name: "private_net"
    ipv4_address: '10.16.0.12'

provisioner:
  name: ansible
  playbooks:
    converge: tasks/main.yml
verifier:
  name: ansible
