---
driver:
  name: docker

platforms:
  - name: instance
    image: "ubuntu:20.04"
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: my_role.yml

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later

