FROM archlinux:latest

# Устанавливаем необходимые инструменты и Python
RUN pacman -Syu --noconfirm && \
  pacman -Sy --noconfirm python python-pip && \
  pacman -Scc --noconfirm  # Очищаем кэш Pacman для уменьшения размера образа

# Устанавливаем обновленный pip
RUN pip install --upgrade pip

# Указываем команду по умолчанию
CMD ["/bin/bash"]
