---
driver:
  name: docker

platforms:
  - name: instance
    image: "altlinux"
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later
