---
driver:
  name: docker

platforms:
  - name: archlinux
    image: "archlinux"
    privileged: true
    command: /sbin/init
    dockerfile: ../dockerfile  # Указываем путь к кастомному Dockerfile

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python
  playbooks:
    converge: converge.yml

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later
...
