---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Start new NGINX container
      community.docker.docker_container:
        name: nginx_new
        image: nginx:latest
        state: started
        recreate: true
        restart: yes
        networks:
          - name: public_net
          - name: private_net
        ports:
          - "8085:80"  # Временно запустить новый контейнер на другом порту
        healthcheck:   # Проверка здоровья контейнера
          test: ["CMD", "curl", "-f", "http://localhost:8081"]
          interval: 30s
          retries: 3
          timeout: 10s

    - name: debug
      debug:
        var: "ansible_facts"
      tags: debug

    - name: Stop old NGINX container after new is healthy
      community.docker.docker_container:
        name: nginx_old
        state: stopped
        when: "'healthy' in docker_container_facts(name='nginx_new').json['State']['Health']['Status']"

    - name: Remove old NGINX container
      community.docker.docker_container:
        name: nginx_old
        state: absent

    - name: Rename new NGINX container to replace the old one
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        recreate: true
        restart: yes
        networks:
          - name: public_net
          - name: private_net
        ports:
          - "8084:80"