version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./app:/app
    expose:
      - "5000"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'         # Ограничение по CPU (половина ядра)
          memory: 512M        # Ограничение памяти (512 МБ)
        reservations:
          cpus: '0.25'        # Минимальное количество CPU (четверть ядра)
          memory: 256M        # Минимально резервируемая память (256 МБ)

  db:
    image: postgres:15
    environment: 
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
      - db
    networks:
      - app-network

networks: 
  app-network: 
    driver: bridge

volumes:
  postgres_data:

   


