version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./app:/app
    expose:
      - "5000"
    networks:
      - app-network

  db:
    image: postgres:15
    environment: 
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
      - db
    networks:
      - app-network

networks: 
  app-network: 
    driver: bridge

volumes:
  postgres_data:

   


