version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./docker-compose-app:/app
    expose:
      - "5000"
    networks:
      - app-network
  db:
    image: postgres:15
    environment: 
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: