version: '3.8'
services:
  app:
    image: nginx
    secrets:
      - my_secret
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
secrets:
  my_secret:
    external: true