# Пример Dockerfile
FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY nginx2.conf /etc/nginx/conf.d/nginx.conf
COPY index.html /usr/share/nginx/html/index.html
