FROM alt:p10

ENV http_proxy=http://10.7.156.140:3128
ENV https_proxy=http://10.7.156.140:3128
ENV no_proxy=127.0.0.1,localhost,adm-alt-update.phg.gazprom.ru

COPY sources.list /etc/apt/sources.list

RUN rm -rf /etc/apt/sources.list.d && \
    apt-get update && apt-get dist-upgrade -y && \
    apt-get install python3 python3-module-pip -y
