version: '3'
services:
  web:
    image: nginx
    ports:
      - "8080"
    volumes:
      - web_data:/usr/share/nginx/html
    networks:
      - app_net

volumes:
  web_data:

networks:
  app_net:
    driver: bridge
