
---
- name: Ensure nginx is installed  
  package:
    name: nginx
    update_cache: true
  notify: Restart nginx
  tags: 
    - install

- name: Проверка сертификата
  community.crypto.x509_certificate_info:
    path: '{{ tls_dir + cert_file }}'
    valid_at:
      point: "+30d"          
  register: result
  ignore_errors: true

- name: Создать новый самоподписанный сертификат
  openssl_certificate:
    path: '{{ tls_dir + cert_file }}'
    privatekey_path: '{{ tls_dir + key_file }}'
    provider: selfsigned       
    state: present
  ignore_errors: true


- name: Create directories for TLS certificates
  file:
    path: "{{ tls_dir }}"
    state: directory
    mode: '0750'
  tags: mkdir
  notify: Restart nginx

- name: Copy TLS files
  copy:
    src: "{{ item }}"
    dest: "{{ tls_dir }}"
    mode: '0600'
  loop:
    - "{{ key_file }}"
    - "{{ cert_file }}"
  notify: Restart nginx 

- name: Manage nginx config template
  template:
    src: nginx.conf.j2
    dest: "{{ conf_file }}"
    mode: '0644'
  notify: Restart nginx
  tags:
    - config

- name: Enable configuration
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
      
- name: Install home page
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: '0644'

- name: Restart nginx
  meta: flush_handlers
  tags:
    - restart
      
- name: "Test it! https://34.31.27.38:443/index.html"
  delegate_to: localhost
  become: false
  uri:
    url: 'https://34.31.27.38:443/index.html'
    validate_certs: false
    return_content: true
  register: this
  failed_when: "'Running on ' in this.content"
  tags:
    - test

