---
- name: "Проверка"  
  hosts: webservers
  tasks:
    - name: "Проверка сертификата"  
      openssl_certificate:
        path: '{{ tls_dir }}'
        state: info
      register: cert_info

      

    - name: Проверка даты окончания
      debug:
        msg: "Срок действия сертификата истекает {{ cert_info.not_after }}"