---
- name: Configure django
  hosts: webservers
  become: true
  vars_files:
    - "vars/external_vars.yml"

  tasks:
    - name: Ensure Python is installed
      package:
        name: python3
        state: present
    
    - name: Ensure pip and venv are installed
      package:
        name:
          - python3-pip
          - python3-venv
          - libpq-dev
        state: present
    

    - name: Проверка
      debug:
        msg: "{{ proj_path }}"

    

    - name: Create a virtual environment
      command:
        cmd: python3 -m venv {{ venv_path }}
        creates:  "{{ venv_path }} /bin/activate"

    - name: Install Django in virtual environment
      pip:
        name: 
          - django
          - psycopg2
        virtualenv:  "{{ venv_path }}"
        state: present
      when: venv_path is defined          


    - name: Create a new Django project
      ansible.builtin.command:
        cmd: "{{ venv_path }}/bin/django-admin startproject myproject {{ proj_path }}"
      args:
        creates: "{{ proj_path }}/manage.py" 
    


    - name: Initialize the database
      postgresql_db:
        name: "{{ db_name }}"
        state: present
        login_user: postgres
        login_password: postgres
        host: 127.0.0.1
        port: 5432
       
    - name: Apply Django migrations
      django_manage:
        command: migrate
        app_path: "{{ proj_path }}"
        virtualenv: "{{ venv_path }}"
      register: result
      changed_when: '"Creating tables" in result.out|default("")'

    - name: Проверка 2
      debug:
        msg: "{{ result }}"