---
- name: Install Docker and Docker Compose
  hosts: ghost
  become: true  # Для выполнения задач от имени суперпользователя
  tasks:
    - name: Установить зависимости
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: true

    - name: Добавить GPG ключ Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавить репозиторий Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Установить Docker
      apt:
        name: docker-ce
        state: latest

    - name: Убедиться, что Docker запущен
      service:
        name: docker
        state: started
        enabled: true

    - name: Скачать Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-linux-aarch64"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Проверка установки Docker
      command: docker --version
      register: docker_version

    - name: Проверка установки Docker Compose
      command: docker compose version
      register: docker_compose_version

    - name: Вывести версии Docker и Docker Compose
      debug:
        msg: 
          - "Docker version: {{ docker_version.stdout }}"
          - "Docker Compose version: {{ docker_compose_version.stdout }}"
