---
- name: Copy multiline string to a file
  hosts: all
  become: true
  tasks:
    - name: Create file with multiline content
      copy:
        content: |
          Department of Computer Science
          A.V. Williams Building
          University of Maryland
          City: College Park
          State: Maryland
        dest: /tmp/multiline_address.txt
