---
- name: Show return value of command module
  hosts: production
  gather_facts: true
  vars:
    tmp: "Переменная в плейбуке"
  tasks:
    - name: Print 
      debug: 
        msg: "{{ tmp }}"
      ignore_errors: true