---
- name: Настройка базы данных
  become: true
  hosts: webservers
  roles:
    - role: database
      db_name: "{{ database_name }}"

- name: Настройка веб-сервера
  become: true
  hosts: webservers
  roles:
    - role: webserver
      listen_port: 80